### ISSUE TITLE
运行index.py出现的错误

### ISSUE THREAD

**Issue by Moonstarwork** [xjr7670/QQzone_crawler#6]
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 317-819-167
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/index.py", line 66, in index
    total_info['first_mood'] = make_date(first_mood)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/util.py", line 26, in make_date
    res = time.gmtime(utstime)
ValueError: Invalid value NaN (not a number)
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:39] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/index.py", line 66, in index
    total_info['first_mood'] = make_date(first_mood)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/util.py", line 26, in make_date
    res = time.gmtime(utstime)
ValueError: Invalid value NaN (not a number)
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:3* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 317-819-167
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/index.py", line 66, in index
    total_info['first_mood'] = make_date(first_mood)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/util.py", line 26, in make_date
    res = time.gmtime(utstime)
ValueError: Invalid value NaN (not a number)
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:39] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
  File "/home/moonstar/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/index.py", line 66, in index
    total_info['first_mood'] = make_date(first_mood)
  File "/home/moonstar/github/QQzone_crawler/get_single_report/util.py", line 26, in make_date
    res = time.gmtime(utstime)
ValueError: Invalid value NaN (not a number)
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:38] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:39] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
8] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [30/Jan/2018 15:13:39] "GET /qqnum=983267850?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by Moonstarwork** [comment]
解决了谢谢
